language: objective-c

before_install:
  - gem install cocoapods -v '0.37.1'

pre-installed:
  - brew update
  - brew install xctool

script: xctool -workspace test.xcworkspace -scheme test test -sdk iphonesimulator